### ISSUE TITLE
Switching to NUC

### ISSUE THREAD

**Issue by NightmareElmo** [JoshuaGarrison27/Home-Assistant-Configuration#8]
Sorry if this is wrong way to do this but i dont really know how github works. I was just curious why you want to change from Hass.io to a docker container on a NUC? I currently run HA in a container but i'm thinking to moving to hass.io on a dedicated Pi, the container has port issues and the Hass.io has the addons, but are there disadvantages to hass.io? Thanks and sorry again

**Comment by binaryn3xus** [comment]
@NightmareElmo Sorry, I missed this notification. The NUC has more power and memory depending on your build. My raspberry pi seems to struggle a bit sometimes due to the amount of zwave devices and such attached to my instance. A coworker of mine was telling me how his instance became way faster when he switched to Docker and a more powerful machine. Dont get me wrong, I love hass.io because it makes some things so simple, such as renewing SSL Certs. If you have anything to share about your experience in your Docker setup, I would love to hear it.

**Comment by NightmareElmo** [comment]
I find the docker setup on my home server very messy with hass.io. I think if i was to redo it I would only have Hass.io on a dedicated machine and not on a home server. But a NUC would do that job well
